insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("computer1", "computer", 100, "samsung", 10, "Samsung is samsung")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("computer2", "computer", 150, "Apple", 5, "Gamsung")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("computer3", "computer", 200, "LG", 8, "Light")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("computer4", "computer", 250, "ASUS", 13, "Cheap")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("running shoes1", "shoes", 14, "NIKE", 12, "Just Do Homework")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("running shoes2", "shoes", 8, "FILA", 10, "Korean brand")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("running shoes3", "shoes", 7, "HEAD", 7, "Cute")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("running shoes4", "shoes", 10, "ADIDAS", 3, "Samdidas")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("backpack1", "bag", 12, "FILA", 5, "Cute back")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("backpack2", "bag", 10, "ADIDAS", 6, "Black")
